### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by r06942072** [r06942072/frontend_BLASTquery#1]
**App** = render 4 components

**YourQuery**

**OurDb**

**Program**

**TimeTravel**

**Comment by r06942072** [comment]
**YourQuery**
- [ ] Upload file can really upload file
https://reactjs.org/docs/forms.html

**Comment by r06942072** [comment]
**OurDb**
- [ ] hover on item, it lights up

- [x] searchBar
similar project: Emoji Search
https://reactjs.org/docs/lifting-state-up.html

- [x] Multiple checkbox for every single organism
reference:
https://medium.com/@tariqul.islam.rony/multiple-checkbox-handling-by-react-js-84b1d49a46c6

**Comment by r06942072** [comment]
**Program**
- [ ] Basic forms, and 5 different layouts to choose

**Comment by r06942072** [comment]
**TimeTravel**
- [ ] Reset: refresh page, and set all components to initial state
- [ ] Submit: http POST action
- [ ] UndoRedo
new funtionality
writing a Reducer Enhancer, input=reducer
https://redux.js.org/recipes/implementing-undo-history
example project:
https://github.com/reduxjs/redux/tree/master/examples/todos-with-undo
using react-forms

**Comment by r06942072** [comment]
**App**
- [ ] Dataflow: db -> App

- [ ] Dataflow: App -> db
start alignment
implement axios library on App/
mimic restAPI, fetch string[] from an url
and pass down data by props to 4 components

- [x] make redux store
https://react-redux.js.org/
communication between components
between YourQuery and Program
between OurDb and Program
